# This is the mac specific config
include kitty-common.conf

background_image /Users/W517620/Documents/flower.jpg
background_image_layout cscaled
background_tint 0.85

background_blur 0

font_size 18
